### ISSUE TITLE
Dependency on 2013111800

### ISSUE THREAD

**Issue by bgurney** [dthies/moodle-qbehaviour_deferredallnothing#2]
Hi,

I have been asked to install this plugin on a Moodle 2.6 installation for a client. The package has a dependency on qbehaviour_deferredfeedback (2013111800) but I cannot find this version anywhere?

Any pointers would be appreciated.

Thanks.

**Comment by dthies** [comment]
Hi Ben,
I have corrected the dependency to a more standard version. If you could please download it from here and test. I will it on moodle.org when I can verify it working.
Thanks for reporting this.

**Comment by bgurney** [comment]
Thanks, that seems to have installed fine!

**Comment by dthies** [comment]
Great!
