### ISSUE TITLE
Invalid string

### ISSUE THREAD

**Issue by atronat** [dthies/moodle-qbehaviour_deferredallnothing#4]
Thank you for a job :)
Small bug: Invalid get_string() identifier: 'plugname' or component 'qbehaviour_deferredallnothing'.

Need replace "plugname" with "pluginname" in file db/mobile.php
https://github.com/dthies/moodle-qbehaviour_deferredallnothing/blob/67b5db226a46b4ee2d2ebfba495ad95f9a9d23ff/db/mobile.php#L37

**Comment by dthies** [comment]
Thanks for reporting this. It should be fixed now.
